name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports: [ '5432:5432' ]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
      NODE_ENV: test
      JWT_SECRET: test-secret
      FRONTEND_ORIGIN: http://localhost:5173
      STRIPE_SECRET_KEY: sk_test_dummy
      STRIPE_WEBHOOK_SECRET: whsec_dummy
      STRIPE_SKIP_SIG_CHECK: 'true'
      STATUS_ENABLED: 'true'
      VITE_API_URL: http://localhost:5002
      COOKIE_SECURE: 'false'
      CORS_ORIGINS: http://localhost:5173

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install (workspaces)
        run: npm ci

      - name: Wait for Postgres (belt & suspenders)
        run: |
          for i in {1..30}; do
            nc -z localhost 5432 && echo "Postgres up" && exit 0
            echo "Waiting for Postgres..."
            sleep 2
          done
          echo "Postgres never became ready" >&2
          exit 1

      - name: Prisma generate (server)
        working-directory: server
        run: npx prisma generate

      - name: Prisma migrate deploy (server)
        working-directory: server
        run: npx prisma migrate deploy

      - name: Lint
        run: npm run lint --workspaces
        continue-on-error: true

      - name: Typecheck (server/client)
        run: npm run typecheck --workspaces
        continue-on-error: true

      - name: Test (server)
        run: npm run test --workspace server
        continue-on-error: true

      - name: Test (client)
        env:
          CI: 'true'
        run: npm run test --workspace client
        continue-on-error: true

      - name: Build (server)
        run: npm run build --workspace server

      - name: Build (client)
        run: npm run build --workspace client

      - name: Upload junit / coverage (if available)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            **/junit*.xml
            **/coverage/**
